### ISSUE TITLE
Support for shap==0.43.0

### ISSUE THREAD

**Issue by detrin** [ing-bank/probatus#234] opened 2023-10-12 17:11 UTC
**Describe the bug**

There was new release of shap https://github.com/shap/shap/releases/tag/v0.43.0, which results in fail when importing from probatus.

**Environment (please complete the following information):**

 - probatus @ git+https://github.com/ing-bank/probatus.git@0be29d027b87a2247dc6d2f180e94c4a36ac8866
 - Python 3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)]
 - OS: macOS

**To Reproduce**

Run
```python
from probatus.feature_elimination import ShapRFECV
```

**Error traceback**

If applicable please provide full traceback of the error.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[82], line 3
      1 import lightgbm
      2 from sklearn.model_selection import RandomizedSearchCV
----> 3 from probatus.feature_elimination import ShapRFECV, EarlyStoppingShapRFECV
      5 params = {
      6     "learning_rate": 0.05,
      7     "colsample_bytree": 0.75,
   (...)
     17     "seed": 1234,
     18 }
     20 # waiting for RandomizedSearchCV support to be solved in probatus
     21 # param_grid = {
     22 #     "num_leaves": [25, 50, 100, 150, 200],
     23 # }

File [~/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/probatus/feature_elimination/__init__.py:21](https://file+.vscode-resource.vscode-cdn.net/Users/danielherman/Documents/projects/PSW_devel/workflow/~/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/probatus/feature_elimination/__init__.py:21)
      1 # Copyright (c) 2020 ING Bank N.V.
      2 #
      3 # Permission is hereby granted, free of charge, to any person obtaining a copy of
   (...)
     17 # IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
     18 # CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
---> 21 from .feature_elimination import ShapRFECV, EarlyStoppingShapRFECV
     23 __all__ = ["ShapRFECV", "EarlyStoppingShapRFECV"]

File [~/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/probatus/feature_elimination/feature_elimination.py:11](https://file+.vscode-resource.vscode-cdn.net/Users/danielherman/Documents/projects/PSW_devel/workflow/~/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/probatus/feature_elimination/feature_elimination.py:11)
      8 from sklearn.model_selection import check_cv
      9 from sklearn.model_selection._search import BaseSearchCV
---> 11 from probatus.utils import (
     12     BaseFitComputePlotClass,
     13     assure_pandas_series,
     14     calculate_shap_importance,
     15     get_single_scorer,
     16     preprocess_data,
     17     preprocess_labels,
     18     shap_calc,
     19 )
     22 class ShapRFECV(BaseFitComputePlotClass):
     23     """
     24     This class performs Backwards Recursive Feature Elimination, using SHAP feature importance.
     25 
   (...)
    100 
    101     """  # noqa

File [~/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/probatus/utils/__init__.py:31](https://file+.vscode-resource.vscode-cdn.net/Users/danielherman/Documents/projects/PSW_devel/workflow/~/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/probatus/utils/__init__.py:31)
     21 from .scoring import Scorer, get_scorers, get_single_scorer
     22 from .arrayfuncs import (
     23     assure_numpy_array,
     24     assure_pandas_df,
   (...)
     29     preprocess_labels,
     30 )
---> 31 from .shap_helpers import shap_calc, shap_to_df, calculate_shap_importance
     32 from .warnings import ApproximationWarning
     33 from ._utils import (
     34     class_name_from_object,
     35     assure_list_of_strings,
     36     assure_list_values_allowed,
     37 )

File [~/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/probatus/utils/shap_helpers.py:26](https://file+.vscode-resource.vscode-cdn.net/Users/danielherman/Documents/projects/PSW_devel/workflow/~/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/probatus/utils/shap_helpers.py:26)
     24 import pandas as pd
     25 from shap import Explainer
---> 26 from shap.explainers._tree import Tree
     27 from shap.utils import sample
     28 from sklearn.pipeline import Pipeline

ImportError: cannot import name 'Tree' from 'shap.explainers._tree' (/Users/danielherman/Documents/projects/PSW_devel/workflow/env/lib/python3.11/site-packages/shap/explainers/_tree.py)
```

**Comment by leo2r** [comment] 2023-11-30 14:50
Same problem for me!!

**Comment by max-franceschi** [comment] 2024-01-16 18:24
Same here, pretty annoying.

**Comment by astrafeng** [comment] 2024-02-11 14:32
Same problem for me!!

**Comment by ReinierKoops** [comment] 2024-03-17 18:45
The issue is due to this: https://github.com/shap/shap/pull/3247 I'll look into changing the code accordingly

**Comment by ReinierKoops** [comment] 2024-03-17 20:36
@yustiks @max-franceschi @xuican @jip333 it should be fixed in SHAP

**Comment by ReinierKoops** [comment] 2024-03-18 21:56
fixed

**Closed** 2024-03-18 21:57 UTC
Labels: bug
